dist: xenial
sudo: required
language: php

cache:
  directories:
    - "$HOME/.composer/cache"

php:
  - 7.3
  - 7.4
  - 8.0
  - nightly
  - hhvm


matrix:
  allow_failures:
    - php: nightly
    - php: hhvm
  fast_finish: true

notifications:
  on_success: never
  on_failure: always

git:
  depth: 1

install:
  - travis_retry composer install --prefer-dist --no-interaction

script:
  - composer check-code
  - if [ "$TRAVIS_PHP_VERSION" == "8.0" ]; then composer test-cov; else composer test; fi

after_script:
  - if [ "$TRAVIS_PHP_VERSION" == "8.0" ]; then composer test-cov-upload; fi
