dist: xenial
sudo: required
language: php

cache:
  directories:
    - vendor
    - $HOME/.composer/cache

php:
  - 7.4
  - 8.0
  - nightly

jobs:
  allow_failures:
    - php: nightly
  fast_finish: true

notifications:
  on_success: never
  on_failure: always

git:
  depth: 1

install:
  - travis_retry composer install --prefer-dist --no-interaction

script:
  - composer check-code
  - if [ "$TRAVIS_PHP_VERSION" == "8.0" ]; then composer test-cov; else composer test; fi

after_success:
  - if [ "$TRAVIS_PHP_VERSION" == "8.0" ]; then composer test-cov-upload; fi
